# Generated by Django 5.0.1 on 2024-01-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
            ],
        ),
    ]
